### ISSUE TITLE
Fails with error "Cannot find module './vendor/jsPDF/jspdf"

### ISSUE THREAD

**Issue by felamaslen** [calvinfroedge/node-jspdf#10]
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './vendor/jsPDF/jspdf'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/fela/code/api/node_modules/node-jspdf/index.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (/Users/fela/code/api/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/Users/fela/code/api/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

**Comment by DefinteIntegral** [comment]
I don't suppose you ever found a solution for this?

**Comment by the-homeless-god** [comment]
I think your folder outside the import folder
Could you `ls -la` your folder structure?
